version: '3'
services:
  
  #backend api
  api:
    image: pedropltm/glucosecontrolapi:latest
    ports:
      - "7121:80"
    networks:
      - glucose-control-network
    depends_on:
      - "mongo"

  #database
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    #volumes:
    #  - /home/pedropltm/source/repos/GlucoseControl/MongoDB:/data/db
    networks:
      - glucose-control-network
  
  #mongodb web admin interface
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: pedro
      ME_CONFIG_BASICAUTH_PASSWORD: "1234as"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    links:
      - mongo
    networks:
      - glucose-control-network

networks:
  glucose-control-network:
    driver: bridge