# Use root/example as user/password credentials
version: '3.1'

networks:
  glucose-control-network:
    driver: bridge

services:
  
  #backend api
  api:
    image: pedropltm/glucosecontrolapi
    volumes:
      - ./API:/API
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - glucose-control-network
    depends_on:
      - "mongo"

  #database
  mongo:
    image: mongo
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: GlucoseControlDevelop
    ports:
      - "27017:27017"
    networks:
      - glucose-control-network
  
  #mongodb web admin interface
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    #environment:
    #  ME_CONFIG_BASICAUTH_USERNAME: dev
    #  ME_CONFIG_BASICAUTH_PASSWORD: "1234as"
    #  ME_CONFIG_MONGODB_PORT: 27017
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    links:
      - mongo
    networks:
      - glucose-control-network

  yarn:
    image: node:16.0.0
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    entrypoint: yarn
    command: --help
    volumes:
      - ./Frontend:/home/node
    networks:
      - glucose-control-network